package CommonCommand;

import java.io.Serializable;


public enum CommandType implements Serializable{
    LOGIN,SIGNUP,STARTPROJECT,MYPROJECT,ALLPROJECT,GETBRANCH,GETCOMMITS,GERCONTRIBUTORS,SUCCESS,ALREADY_EXISTS , GETPROJECT , GETFILE,GETPULL,
    LISTBRANCH,LISTCOMMITS,ListCONTRIBUTORS,GETPUSH,ADDBRANCH,ADDCONTRIBUTOR,GETPROFILE,GETLISTUSER,GetDiffrent,GetDiffFile,GetNewEvent,
    GETMERGE , Follow_Project,MyFollowProjects , GetPullAndMerge;  
}
